name: Test backend

on:
  push:
    paths:
      - server/**
      - .github/workflows/**
  pull_request:
    paths:
      - server/**
      - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Test with Gradle
        working-directory: ./server
        run: ./gradlew testClasses
